# Generated by Django 4.1.5 on 2023-01-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="i18nlog",
            name="value",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="i18nlog",
            unique_together={("key", "locale")},
        ),
    ]
